<?php
/**
 * Mageplaza_SocialLogin extension
 *                     NOTICE OF LICENSE
 *
 *                     This source file is subject to the MIT License
 *                     that is bundled with this package in the file LICENSE.txt.
 *                     It is also available through the world-wide-web at this URL:
 *                     http://opensource.org/licenses/mit-license.php
 *
 * @category  Mageplaza
 * @package   Mageplaza_SocialLogin
 * @copyright Copyright (c) 2016
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="social-login block-container forgot" style="display:none">
    <div class="social-login-title">
        <h2 class="forgot-pass-title">
            <?php echo __('Forgot Password') ?>
        </h2>
    </div>
    <div class="block col-mg mg-12">
        <div class="block-content">
            <form class="form-password-forget"
                  id="social-form-password-forget"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */
                echo __('* Required Fields') ?>">
                    <div class="field note"><?php /* @escapeNotVerified */
                        echo __('Please enter your email address below to receive a password reset link.'); ?></div>
                    <div class="field email required">
                        <label for="email_address" class="label"><span><?php /* @escapeNotVerified */
                                echo __('Email') ?></span></label>

                        <div class="control">
                            <input type="email" name="email" alt="email" id="email_address" class="input-text"
                                   value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                    <?php echo $block->getChildHtml('forgot.captcha'); ?>

                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="button" class="action send primary"><span><?php /* @escapeNotVerified */
                                echo __('Submit') ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action back" href="#"><span><?php /* @escapeNotVerified */
                                echo __('Go back') ?></span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
