<?php if ($block->isEnabled()): ?>
    <div class="actions-toolbar social-btn twitter-login">
        <div class="primary">
            <button class="action btn_twitter_login" id="btn_twitter_login" type="button">
                <span>
                    <span><?php echo __('Twitter Sign In') ?></span>
                </span>
            </button>
        </div>
    </div>
    <script>
        require(['Mageplaza_SocialLogin/js/sociallogin'], function (SocialLoginPopup) {
            $$('.btn_twitter_login').each(function (el) {
                return $(el).observe('click', function() {
                    var twPopup = new SocialLoginPopup();
                    twPopup.openPopup('<?php echo $block->getLoginUrl()?>', '<?php echo __('Login By Twitter')?>');
                });
            });
        });
    </script>
<?php endif; ?>