<?php if ($block->isEnabled()): ?>
	<div class="actions-toolbar social-btn vk-login">
        <div class="primary">
            <button class="action btn-vk btn_vk_login" id="btn_vk_login" type="button">
                <span>
                    <span><?php echo __('Vkontakte Sign In') ?></span>
                </span>
            </button>
        </div>
    </div>
	<script>
        require(['Mageplaza_SocialLogin/js/sociallogin'], function (SocialLoginPopup) {
			$$('.btn_vk_login').each(function (el) {
				return $(el).observe('click', function() {
					var vkPopup = new SocialLoginPopup();
					vkPopup.openPopup('<?php echo $block->getLoginUrl()?>', '<?php echo __('Login By Vkontakte')?>');
				});
			});
		});
    </script>
<?php endif; ?>